2023-03-01 10:45:39.888 | INFO     | __main__:run:19 - 注册用户服务
2023-03-01 10:49:49.276 | INFO     | __main__:run:18 - 注册用户服务
2023-03-01 10:50:13.441 | INFO     | __main__:run:18 - 注册用户服务
2023-03-01 10:50:46.030 | INFO     | __main__:run:18 - 注册用户服务
2023-03-01 10:50:52.877 | ERROR    | grpc._server:_call_behavior:444 - An error has been caught in function '_call_behavior', process 'MainProcess' (21278), thread 'ThreadPoolExecutor-0_0' (140391902480128):
Traceback (most recent call last):

  File "/mnt/c/Users/Administrator/AppData/Local/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 795, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7faf9e6cc820>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7faf9e6cc820>
          │    └ <bound method Thread._bootstrap of <Thread(ThreadPoolExecutor-0_0, started daemon 140391902480128)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7faf9e6cc820>

  File "/home/llloo/.pyenv/versions/3.8.9/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fafa6db2ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 140391902480128)>
  File "/home/llloo/.pyenv/versions/3.8.9/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fafa6db29d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 140391902480128)>
  File "/home/llloo/.pyenv/versions/3.8.9/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 140391902480128)>
    │    │        │    └ (<weakref at 0x7faf9e6d4310; to 'ThreadPoolExecutor' at 0x7fafa50be070>, <_queue.SimpleQueue object at 0x7faf9e7551d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 140391902480128)>
    │    └ <function _worker at 0x7fafa52264c0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 140391902480128)>
  File "/home/llloo/.pyenv/versions/3.8.9/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fafa52265e0>
    └ <concurrent.futures.thread._WorkItem object at 0x7faf9e6cc4f0>
  File "/home/llloo/.pyenv/versions/3.8.9/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7faf9e6cc4f0>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x7faf9e6c8e00>, <grpc._server._RPCState object at 0x7faf9e6cc8b0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7faf9e6cc4f0>
             │    └ <function _unary_response_in_pool at 0x7faf9e6c3940>
             └ <concurrent.futures.thread._WorkItem object at 0x7faf9e6cc4f0>
  File "/home/llloo/.pyenv/versions/3.8.9/envs/ms/lib/python3.8/site-packages/grpc/_server.py", line 561, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method UserService.getUserList of <user_server.handler.user.UserService object at 0x7faf9e75e040>>
                        │              │          └ <grpc._server._RPCState object at 0x7faf9e6cc8b0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7faf9e6c8e00>
                        └ <function _call_behavior at 0x7faf9e6c3550>
> File "/home/llloo/.pyenv/versions/3.8.9/envs/ms/lib/python3.8/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7faf9e6ccc40>
                           │        └ page: 1
                           │          pageSize: 10
                           │          
                           └ <bound method UserService.getUserList of <user_server.handler.user.UserService object at 0x7faf9e75e040>>

  File "/mnt/d/tutor/mxshop_servers/user_server/handler/user.py", line 35, in getUserList
    1/0

ZeroDivisionError: division by zero
2023-03-01 10:56:27.630 | INFO     | __main__:run:17 - 注册用户服务
2023-03-01 21:09:00.818 | INFO     | __main__:run:17 - 注册用户服务
2023-03-02 14:25:21.671 | INFO     | __main__:run:17 - 注册用户服务
